version: "3.9"  # optional since v1.27.0
services:
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "5000:4000"    
    environment:
      - PORT=4000
    command: npm start