version: "3.9"  # optional since v1.27.0
services:
  react_app:
    container_name: appserver
    build:
      context: ./frontend
      args:
        - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm start 
  
  redis:
    image: redis
    container_name: redis
    # networks:
    #   static-network:
    #     ipv4_address: 172.20.128.3
  
  mongo:
    image: mongo
    container_name: dbserver
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password_1234_mongo
      - MONGO_INITDB_DATABASE=mydb
    volumes:
      - mongo-db:/data/db    
    # command: 
    #         - '--logpath'
    #         - '/var/log/mongodb/mongod.log'
    #         - '--profile'
    #         - '2'
    depends_on:      
      - redis     
    # networks:
    #   static-network:
    #     ipv4_address: 172.20.128.2  
  
  node_app:
    container_name: backend     
    build:
      context: ./backend      
      args:
        - NODE_ENV=development    
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules 
    environment:
      - NODE_ENV=development
      - PORT=4000      
      - MONGO_USER=mongoadmin
      - MONGO_PASSWORD=password_1234_mongo
      - SESSION_SECRET=12345678
    command: npm run dev
    depends_on:     
      - mongo
      - redis
      ## networks:
      ##   static-network:
      ##     ipv4_address: 172.20.128.1
      # ports:
      #   - "4000:4000" 

  nginx:
    image: nginx:latest
    container_name: webserver   
    build : 
      context: ./nginx
    ports:
      - "3000:80"
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    depends_on:     
      - node_app
      - react_app  
  
volumes:
  mongo-db:
  node_modules:

# networks:
#   static-network:
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16
#           # #docker-compose v3+ do not use ip_range
#           ip_range: 172.28.5.0/24